### PR TITLE
Add validation

### PR DESCRIPTION
**Pull request by finwo**
@hville I thought this was missing

### CODE REVIEW

**Comment by hville** [comment]
Thanks. Noticed I had some un-commited pending changes so I messed-up things a little. My bad. I wonder what is the use case for square validation. Games?

This small module is mostly concerned about large sampling sets for monte-carlo simulations in lieu of brute random values. This is why rows are generated one at a time since the full square matrix is not required. The validation is only for testing the module itself.

For full matrix handling, looks like [pinalbhatt/latinSquare](https://github.com/pinalbhatt/latinSquare) is a better bet and it already has a validation part.

**Comment by finwo** [comment]
@hville I'm planning the use it in the following project: https://github.com/cdeps/ppsh

**Comment by hville** [comment]
Thanks for sharing, I did not know about OTG. I was keen to keep the module tiny and doing only one thing but since some validation is required for the tests anyways I could just move the validation helpers to a seperate file so that you could do `var validation = require('latin-square/validation')`. 

I had a look at [/cdeps/ppsh](https://github.com/cdeps/ppsh) at it looks like all the error messages are not used. If that is the case, I would rather stick with `Booleans` since `if (validate(greateStuff))` feels more intuitive than the negative.

I it is ok with you (seperate file and Boolean results) I can just do it and publish it right away. No need for a PR.

**Comment by finwo** [comment]
You're welcome.

Since I haven't build logging & a verbose mode yet, the messages aren't used. The idea was te later on be able te display what's wrong, so small fixes to keys may even be possible.

I like the idea of moving it to `require('latin-square/validation')` so you can re-use validation code inside the module itself. 

Ok if I do that later today?

**Comment by hville** [comment]
Ok. Done. I was not too hot on the message string thing since it unilingual and can't be configured but no harm I guess. Just published on github and on npm. you can now require the validation. Cheers!

**Comment by finwo** [comment]
I've moded the validation to a seperate file now, as you suggested. Havan't made the test use it yet (or mix it up another way).

**Comment by hville** [comment]
Looks like out efforts crossed. As stated in my previous message, the change was already made and published. The new `test.js` commit failed so I have just added the few additional test cases and republished. Note that I have made a minor change to the 'Empty matrix message'.

**Pull request closed without merging**
